config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/create'
  get 'bookmarks/new'
  get 'bookmarks/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'movies', to: 'movies#index'

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark = Bookmark.new(list: @list, movie: @movie, comment: params[:bookmark][:comment])

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    if @bookmark.destroy
      redirect_to list_path(@list), status: :see_other
    end
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end


  private

  def params_list
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>
<br>

<div class="container">
<h1>Create a new Bookmark</h1>
<%= simple_form_for [@list, @bookmark], url: list_bookmarks_path(@list) do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all, include_blank: "Select a movie", input_html: {class: "form-control selectpicker", "data-live-search": "true", "data-style": "btn-outline-secondary"}%>
  <%= f.submit class:"btn btn-success" %>
<% end %>

<h3><%= link_to "Back to list", list_path(@list), class:"btn btn-light" %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/NavBar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

<% @lists.each do |list| %>
<div class="container">
<ul class="list-group">
<li class="list-group-item"> <%= list.name %></li>
<li class="list-group-item"> <%= link_to 'List Show', list_path(list) %></li>
</ul>
<br>
</div>

<%end %>
<div class="container">
<%= link_to "New List", new_list_path, class: "btn btn-success" %>
</div>

app/views/lists/new.html.erb
<br>

<div class="container">
<h1>Create a new List</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit class:"btn btn-success" %>
<% end %>

<h3><%= link_to "Back to list", lists_path, class:"btn btn-light" %></h3>
</div>

app/views/lists/show.html.erb
<p> <%= @list.name %></p>

lister les films qui sont dans la list

<br>

<% @list.bookmarks.each do |bookmark| %>

<ul>
<li><%= bookmark.movie.title  %></li>
<li><%= bookmark.comment  %></li>
<li><%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
</ul>

<% end %>


<%= link_to "Add a Bookmark", new_list_bookmark_path(@list) %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

<% @movies.each do |movie| %>
<div class="container">
<ul class="list-group">
<li class="list-group-item"> <%= movie.title %></li>
<li class="list-group-item"> <%= movie.overview %></li>
<li class="list-group-item"> <%= movie.poster_url %></li>
<li class="list-group-item"> <%= movie.rating %> / 5</li>
</ul>
<br>
</div>
<%end %>

app/views/shared/_NavBar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Movie List</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <%= link_to "Movies", movies_path, class:"nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Lists", lists_path, class:"nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <%= link_to "Create List", new_list_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>